# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15)),
                ('company_name', models.CharField(max_length=255)),
                ('coupon', models.DecimalField(decimal_places=2, max_digits=2)),
                ('maturity_date', models.DateTimeField()),
                ('bond_type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Etf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=30)),
                ('fund_family', models.CharField(max_length=30)),
                ('beta', models.DecimalField(decimal_places=2, max_digits=2)),
                ('alpha', models.DecimalField(decimal_places=2, max_digits=2)),
                ('r_squared', models.DecimalField(decimal_places=2, max_digits=3)),
                ('sharpe_ratio', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15)),
                ('company_name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=30)),
                ('industry', models.CharField(max_length=30)),
                ('market_capitalization', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
