# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bond',
        ),
        migrations.DeleteModel(
            name='Etf',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
