# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0004_auto_20160130_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bond',
            name='bond_type',
        ),
        migrations.AddField(
            model_name='bond',
            name='moody_rating',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='bond',
            name='sp_rating',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='bond',
            name='coupon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
