# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0005_auto_20160202_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='maturity_date',
            field=models.DateField(),
        ),
    ]
