# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment_policy',
            name='expected_inflation',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='investment_policy',
            name='expected_return',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
