# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20160208_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
