# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_risk_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='federal_tax',
            field=models.DecimalField(choices=[(10, '10%'), (15, '15%'), (25, '25%'), (28, '28%'), (33, '33%'), (35, '35%'), (39.6, '39.6%')], decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='state_tax',
            field=models.DecimalField(choices=[(0, '0.00%'), (1, '1.00%'), (1.4, '1.40%'), (1.5, '1.50%'), (1.75, '1.75%'), (2, '2.00%'), (2.5, '2.50%'), (3, '3.00%'), (3.5, '3.50%'), (4, '4.00%'), (4.5, '4.50%'), (5, '5.00%'), (5.25, '5.25%'), (5.5, '5.50%'), (5.9, '1.90%'), (6, '6.00%'), (6.37, '6.37%'), (6.5, '6.50%'), (6.85, '6.85%'), (7, '7.00%'), (7.5, '7.50%'), (7.85, '.85%'), (8, '8.00%'), (8.5, '8.50%'), (8.97, '8.97%'), (9, '9.00%'), (9.5, '9.50%'), (10, '10.00%'), (10.5, '10.50%'), (11, '11.00%')], decimal_places=2, max_digits=10),
        ),
    ]
